spring:
  application:
    name: bored-service-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 129.28.157.98:26379, 129.28.157.98:26380, 129.28.157.98:26381

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      default-filters:
        # 熔断降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/defaultfallback'
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
      #          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
      ##          filters:
      #            - StripPrefix=1
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: BORED-SERVICE-CONSUMER-USERUPDATE
          uri: lb://bored-service-consumer-userupdate
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE-CONSUMER-APPLY
          uri: lb://bored-service-consumer-apply
          predicates:
            - Path=/api/apply/**
          filters:
            - StripPrefix=1
            # 熔断降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultfallback'
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 800
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 800
        - id: BORED-SERVICE=CONSUMER-LOGIN
          uri: lb://bored-service-consumer-login
          predicates:
            - Path=/api/login/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-REG
          uri: lb://bored-service-consumer-reg
          predicates:
            - Path=/api/reg/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-PAL
          uri: lb://bored-service-consumer-pal
          predicates:
            - Path=/api/pal/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-FRIDND
          uri: lb://bored-service-consumer-friend
          predicates:
            - Path=/api/friend/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-SPACE
          uri: lb://bored-service-consumer-space
          predicates:
            - Path=/api/space/**
          filters:
            - StripPrefix=1
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000
  shareSecurityContext: true

server:
  port: 9000

feign:
  sentinel:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug

#排除用户验证路径
exclude-paths-list:
  paths[0]: "/reg/useradd"
  paths[1]: "/login/login"
  paths[2]: "hauwei: 4096"
  paths[3]: "qq: 1024"


