spring:
  application:
    name: bored-service-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
#          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
##          filters:
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true
      routes:
        - id: BORED-SERVICE-CONSUMER-USERUPDATE
          uri: lb://bored-service-consumer-userupdate
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE-CONSUMER-APPLY
          uri: lb://bored-service-consumer-apply
          predicates:
            - Path=/api/apply/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-LOGIN
          uri: lb://bored-service-consumer-login
          predicates:
            - Path=/api/login/**
          filters:
            - StripPrefix=1
        - id: BORED-SERVICE=CONSUMER-REG
          uri: lb://bored-service-consumer-reg
          predicates:
            - Path=/api/reg/**
          filters:
            - StripPrefix=1

server:
  port: 9000

feign:
  sentinel:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug
